#!/bin/bash

set -eo pipefail

###########################################################
# This script overwrites the default kube-dns config
# generated by acs-engine. Specifically it does the following 3 things:
# - Ensures the containers in the pods have a Guaranteed QOS class
# - Ensures that dnsmasq does not pass external dns queries to kubedns
# - Enables logging of dns queries in the dnsmasq container
###########################################################

KUBE_DNS_DEPLOYMENT_FILE_PATH="/etc/kubernetes/addons/kube-dns-deployment.yaml"

if grep -q 'Ubuntu' /etc/os-release 2>/dev/null; then
    # Use systemd service
    install -m 0644 kubedns.manifest ${KUBE_DNS_DEPLOYMENT_FILE_PATH}
fi
